dupe:
  chicken:
    enable: false # boolean true or false
    period: 1  # double 分钟
  donkey:
    enable: false # boolean true or false
  mine_and_place:
    enable: false # boolean true or false
    amount: 10 # example: 10+1 dupe, mine 10 this block, you'll get 1 more block.
  item_frame:
    enable: false
    # it means if you rotate item in the frame you may get more item.
    odds: 75 # percent 百分比 概率 odds
  command:
    enable: false
    times: 4

limits:
  CrystalSpeed:
    enable: false
    max_period: 50 # millisecond 毫秒
  ChunkEntityAmount:
    enable: false
    max_entity: 10
  AntiFlight:
    enable: false
  IllegalEnchantments: # 俗称32k
    enable: false
    DropperBypass: true

