name: AnarchyCore
version: '${version}'
main: me.foshou.plugins.anarchy.core.Main
api-version: '1.19'
authors: [Sunshine_Light_]
description: A Plugin for Anarchy Servers.
permissions:
  anarchy.dupe.chicken:
    default: op
    description: Chicken Dupe Permission
  anarchy.dupe.donkey:
    default: op
    description: Donkey Dupe Permission
  anarchy.dupe.shulker:
    default: op
    description: Shulker Box Dupe Permission
  anarchy.dupe.frame:
    default: op
    description: Item Frame Dupe Permission
  anarchy.dupe.command:
    default: op
    description: Command Dupe Permission
  anarchy.limits.bypass:
    default: op
commands:
  anarchycore:
    description: Plugin main command
    usage: /<command>
    aliases: [ anarchy, core, great, nb, cls, verygood, 666 ]
  suicide:
    description: Kill yourself
    usage: /<command>
    aliases: [ kill, 514, 520, have-kit, backdoor, wuzi, 物资, 后门 ]
  stat:
    description: Stats Searching
    usage: /<command> <player>
    aliases: [ stats, statistic, statistics, player_stat ]